# Generated by Django 5.2.3 on 2025-06-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarDeliveryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Kichik", "Kichik yuk"),
                            ("Orta", "Orta yuk"),
                            ("Katta", "Katta yuk"),
                        ],
                        default="Kichik",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarTaxiType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Ekanom", "Ekanom"),
                            ("Komfort", "Komfort"),
                            ("Lux", "Lux"),
                        ],
                        default="Ekanom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, verbose_name="Yuk mashina turi"),
                ),
                (
                    "height",
                    models.PositiveSmallIntegerField(
                        verbose_name="Yuk mashina balandligi"
                    ),
                ),
                (
                    "width",
                    models.PositiveSmallIntegerField(verbose_name="Yuk mashina eni"),
                ),
                (
                    "length",
                    models.PositiveSmallIntegerField(
                        verbose_name="Yuk mashina uzunligi"
                    ),
                ),
                (
                    "max_weight",
                    models.PositiveSmallIntegerField(
                        verbose_name="Qancha yuk kotara oladi?"
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=10, verbose_name="Yuk mashina raqami"),
                ),
                (
                    "price_km",
                    models.PositiveSmallIntegerField(verbose_name="1 km uchun narx"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carDelivery_type",
                        to="core.cardeliverytype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarCargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, verbose_name="Yuk mashina turi"),
                ),
                ("height", models.FloatField(verbose_name="Yuk mashina balandligi")),
                ("width", models.FloatField(verbose_name="Yuk mashina eni")),
                ("length", models.FloatField(verbose_name="Yuk mashina uzunligi")),
                (
                    "max_weight",
                    models.FloatField(verbose_name="Qancha yuk kotara oladi?"),
                ),
                (
                    "number",
                    models.CharField(max_length=10, verbose_name="Yuk mashina raqami"),
                ),
                (
                    "price_km",
                    models.PositiveSmallIntegerField(verbose_name="1 km uchun narx"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cardeliverytype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarTaxi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Mashina nomi")),
                (
                    "number",
                    models.CharField(max_length=10, verbose_name="Mashina raqami"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Mashina bazaga qoshilgan vaqt"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cartaxitype",
                    ),
                ),
            ],
        ),
    ]
